name: echopop
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  # Computational stack
  - awkward
  - lmfit
  - numpy
  - openpyxl
  - pandas
  - scipy
  # Spatial stack
  - geopandas
  - geopy
  - pyproj
  - shapely
  - verde
  # Validation stack
  - pandera>=0.25
  - pydantic>=2.0.0
  - traitlets
  # Jupyter stack
  - ipympl
  - jupyter_bokeh>=3.0.5
  # Static visualization stack
  - cartopy
  - matplotlib
  # Interactive visualization stack
  - bokeh
  - geoviews
  - holoviews
  - ipywidgets
