# This YAML file is a configuration file for all
# initialization parameters used in Echopop

---
  #####################################################################################################################
  # Survey data processing#
  ########################
  # Jolly and Hampton (1990) stratified mean calculation
  stratified_survey_mean_parameters:
    strata_transect_proportion: 0.75                          # percent of Jolly-Hampton transects in each stratum
    num_replicates: 10000                                         # number of resample replicates

  #####################################################################################################################
  # Biological data processing#
  ########################
  # Jolly and Hampton (1990) stratified mean calculation
  bio_hake_len_bin: [                   # length sequence array 2 - 80 cm. This specifies the bin centers!
                  2,                    # start of bin centers
                  80,                   # end of bin centers
                  40                    # number of bins in total
  ]

  bio_hake_age_bin: [                   # age sequence array: year - age  1-22
                  1,                    # start of sequence
                  22,                   # end of sequence
                  22                    # number of points in the sequence
  ]

  #####################################################################################################################
  # Log-linear regression#
  ########################
  # Target strength (TS) - length (L) regression: TS=m*log10(L)+b
  TS_length_regression_parameters:
    pacific_hake:                         # corresponding species text code
      number_code: 22500                  # species number code
      TS_L_slope: 20.0                    # the 'm' or 'slope' parameter
      TS_L_intercept: -68.0               # the 'b' or 'y-intercept'
      length_units: cm                    # units for L used in regression/relationship

  #####################################################################################################################
  # Geospatial settings#
  ########################
  geospatial:
    init: epsg:4326                       # EPSG integer code for geodetic parameter dataset

  #####################################################################################################################
  # kriging parameters#
  #####################
  kriging_parameters:
    A0: 6.25                              # base area of the grid cell
    longitude_reference: -124.78338       # longitude reference for kriging mesh adjustment
    longitude_offset: -124.78338          # longitudinal offset for kriging mesh adjustment
    latitude_offset: 45.0                 # latitudinal offset for kriging mesh adjustment

  #####################################################################################################################
...
